### ISSUE TITLE
发起支付报错

### ISSUE THREAD

**Issue by ZeroExact** [Iseason2000/SakuraPurchase#10]
paper-1.20.1-65
openjdk 17.0.8
```
[16:47:58] [Server thread/INFO]: ZeroExact issued server command: /sakurapurchase pay ALIPAY default ZeroExact 1
[16:47:59] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/INFO]: [SakuraPurchasePlugin] 用户 ZeroExact 发起 支付宝 支付,金额: 1.0 订单号: 1692095913885081601
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: java.awt.AWTError: Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.desktop/java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1171)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at SakuraPurchasePlugin-1.1.7.jar//top.iseason.bukkit.sakurapurchaseplugin.util.QRCodeUtil.generateQRcode(QRCodeUtil.kt:78)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at SakuraPurchasePlugin-1.1.7.jar//top.iseason.bukkit.sakurapurchaseplugin.util.MapUtil.generateQRMap(MapUtil.kt:82)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at SakuraPurchasePlugin-1.1.7.jar//top.iseason.bukkit.sakurapurchaseplugin.manager.PurchaseManager.purchase(PurchaseManager.kt:61)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at SakuraPurchasePlugin-1.1.7.jar//top.iseason.bukkit.sakurapurchaseplugin.command.CommandsKt$mainCommand$1$2.invoke$lambda$3(Commands.kt:80)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at SakuraPurchasePlugin-1.1.7.jar//top.iseason.bukkit.sakurapurchaseplugin.libs.core.command.CommandNode.onCommand$lambda$7(CommandNode.kt:232)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:48:05] [Craft Scheduler Thread - 9 - SakuraPurchasePlugin/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Iseason2000** [comment]
请在服务端启动参数里添加 -Djava.awt.headless=true

**Comment by ZeroExact** [comment]
问题已解决，非常感谢
